Init snake_cases_fixes
Entropy1729/ARC20_leo pull request #23
Opened 2022-09-16 20:48 UTC by EdVeralli

WIP - Snake_Cases fixes in function names

2022-09-19 18:44 UTC, Loco1982 requested changes
Also there's a typo in the variable called "minimun", it should be "minimum". It's called a couple of times, particularly in the tests

2022-09-19 18:44 UTC, Loco1982 commented on src/main.leo
> +	let test_balanceof_bool: bool = false;
```suggestion
	let test_balance_of_bool: bool = false;
```

2022-09-19 18:44 UTC, Loco1982 commented on src/main.leo
> +		test_balanceof_bool = true;
```suggestion
		test_balance_of_bool = true;
```

2022-09-19 18:44 UTC, Loco1982 commented on src/main.leo
> +	return test_balanceof_bool;
```suggestion
	return test_balance_of_bool;
```

2022-09-19 19:19 UTC, EdVeralli commented on src/main.leo
> +		test_balanceof_bool = true;
Yes, you are right one more time..

2022-09-19 19:28 UTC, EdVeralli commented
> Also there's a typo in the variable called "minimun", it should be "minimum". It's called a couple of times, particularly in the tests

I´ll resolve it.

2022-09-20 14:26 UTC, Loco1982 approved these changes
LGTM

2022-09-20 14:51 UTC, pablodeymo approved these changes
LGTM

2022-09-20 14:52 UTC, merged